name: Docker MySQL healthchecker

on: [push]

env:
  DOCKER_TAG: latest
  DOCKER_IMAGE_DHUB: matthewbaggett/mysql-proxy-health

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to registries
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build the image
      run: docker build . --file Dockerfile --tag mysql-proxy
    - name: Tag image
      run: |
        docker tag mysql-proxy $DOCKER_IMAGE_DHUB:$DOCKER_TAG
    - name: Publish image to Registries
      run: |
        docker push $DOCKER_IMAGE_DHUB:$DOCKER_TAG

